### ISSUE TITLE
PC actor won't open in v7.5.0-alpha.1

### ISSUE THREAD

**Issue by marksjus** [n3dst4/gumshoe-fvtt#504]
Log from console:

commons.js:8772 Foundry VTT | Created Actor with id [Egv5IZm7EPQoSX0X]
foundry.js:753 Error: An error occurred while rendering $2 40. Syntax error, unrecognized expression: #$2-Actor-Egv5IZm7EPQoSX0X
    at se.error (jquery.min.js:2:13759)
    at se.tokenize (jquery.min.js:2:21770)
    at se.select (jquery.min.js:2:22597)
    at Function.se [as find] (jquery.min.js:2:7116)
    at S.fn.init.find (jquery.min.js:2:25167)
    at new S.fn.init (jquery.min.js:2:25656)
    at S (jquery.min.js:2:1051)
    at get element [as element] (foundry.js:5599:12)
    at n._render (foundry.js:6452:22)
    at n.render (foundry.js:5693:10)
onError @ foundry.js:753
investigator-27edc60c.js:14831 datas Array(62)
commons.js:8772 Foundry VTT | Created Item with id [y3R1HhbMV3XnKqNZ] in parent Actor [Egv5IZm7EPQoSX0X]
foundry.js:753 Error: An error occurred while rendering $2 40. Syntax error, unrecognized expression: #$2-Actor-Egv5IZm7EPQoSX0X
    at se.error (jquery.min.js:2:13759)
    at se.tokenize (jquery.min.js:2:21770)
    at se.select (jquery.min.js:2:22597)
    at Function.se [as find] (jquery.min.js:2:7116)
    at S.fn.init.find (jquery.min.js:2:25167)
    at new S.fn.init (jquery.min.js:2:25656)
    at S (jquery.min.js:2:1051)
    at get element [as element] (foundry.js:5599:12)
    at n._render (foundry.js:6452:22)
    at n.render (foundry.js:5693:10)
onError @ foundry.js:753
commons.js:8772 Foundry VTT | Created 62 Item documents in parent Actor [Egv5IZm7EPQoSX0X]
foundry.js:753 Error: An error occurred while rendering $2 40. Syntax error, unrecognized expression: #$2-Actor-Egv5IZm7EPQoSX0X
    at se.error (jquery.min.js:2:13759)
    at se.tokenize (jquery.min.js:2:21770)
    at se.select (jquery.min.js:2:22597)
    at Function.se [as find] (jquery.min.js:2:7116)
    at S.fn.init.find (jquery.min.js:2:25167)
    at new S.fn.init (jquery.min.js:2:25656)
    at S (jquery.min.js:2:1051)
    at get element [as element] (foundry.js:5599:12)
    at n._render (foundry.js:6452:22)
    at n.render (foundry.js:5693:10)
onError @ foundry.js:753
foundry.js:753 Error: An error occurred while rendering $2 40. Syntax error, unrecognized expression: #$2-Actor-Egv5IZm7EPQoSX0X
    at se.error (jquery.min.js:2:13759)
    at se.tokenize (jquery.min.js:2:21770)
    at se.select (jquery.min.js:2:22597)
    at Function.se [as find] (jquery.min.js:2:7116)
    at S.fn.init.find (jquery.min.js:2:25167)
    at new S.fn.init (jquery.min.js:2:25656)
    at S (jquery.min.js:2:1051)
    at get element [as element] (foundry.js:5599:12)
    at n._render (foundry.js:6452:22)
    at n.render (foundry.js:5693:10)
onError @ foundry.js:753

**Comment by n3dst4** [comment]
Fixed (?) probably (??) in [v7.5.0-alpha.2](https://github.com/n3dst4/gumshoe-fvtt/releases/tag/v7.5.0-alpha.2)

This was 100% one of the weirdest bugs I've ever seen.

**Comment by marksjus** [comment]
Fixed. At least for me :D
